export const FETCH_MOVIE_DETAILS= "FETCH_MOVIE_DETAILS";
export const FETCH_MOVIE_DETAILS_SUCCESS= "FETCH_MOVIE_DETAILS_SUCCESS";
export const FETCH_MOVIE_DETAILS_FAILED= "FETCH_MOVIE_DETAILS_FAILED";
export const EMPTY_MOVIE_DETAILS= "EMPTY_MOVIE_DETAILS";
export const FETCH_MOVIE_LIST= "FETCH_MOVIE_LIST";
export const FETCH_MOVIE_LIST_SUCCESS= "FETCH_MOVIE_LIST_SUCCESS";
export const FETCH_MOVIE_LIST_FAILED= "FETCH_MOVIE_LIST_FAILED";
