export const LOGGED_IN= "LOGGED_IN";
export const LOGGED_OUT= "LOGGED_OUT";
export const SIGN_UP= "SIGN_UP";
export const FORGOT_PASSWORD= "FORGOT_PASSWORD";
export const ADD_GOAL= "ADD_GOAL";
export const DELETE_GOAL= "DELETE_GOAL";
export const EDIT_GOAL= "EDIT_GOAL";
export const CHANGE_THEME= "CHANGE_THEME";
export const LOGIN_SUCCESS= "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS= "LOGOUT_SUCCESS";
export const FETCH_GOALS= "FETCH_GOALS";
export const FETCH_GOALS_SUCCESS= "FETCH_GOALS_SUCCESS";
export const FETCH_GOALS_FAILED= "FETCH_GOALS_FAILED";
export const FETCH_IMAGE= "FETCH_IMAGE";
export const FETCH_IMAGE_SUCCESS= "FETCH_IMAGE_SUCCESS";
export const FETCH_IMAGE_FAILED= "FETCH_IMAGE_FAILED";
export const FETCH_MOVIE_DETAILS= "FETCH_MOVIE_DETAILS";
export const FETCH_MOVIE_DETAILS_SUCCESS= "FETCH_MOVIE_DETAILS_SUCCESS";
export const FETCH_MOVIE_DETAILS_FAILED= "FETCH_MOVIE_DETAILS_FAILED";
export const EMPTY_MOVIE_DETAILS= "EMPTY_MOVIE_DETAILS";
export const FETCH_MOVIE_LIST= "FETCH_MOVIE_LIST";
export const FETCH_MOVIE_LIST_SUCCESS= "FETCH_MOVIE_LIST_SUCCESS";
export const FETCH_MOVIE_LIST_FAILED= "FETCH_MOVIE_LIST_FAILED";




export const FETCH_LIST= "FETCH_LIST";
// export const SIGN_UP= "SIGN_UP";
